name = "CLAHE"
uuid = "6c2d17af-c44a-4bcc-8d98-2becef92ce1b"
version = "0.1.0"
authors = ["John Gerrard Holland <john_holland1@brown.edu>"]

[deps]
ImageBase = "c817782e-172a-44cc-b673-b171935fbb9e"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ImageContrastAdjustment = "f332f351-ec65-5f6a-b3d1-319c6670881a"

